// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-YRvgK3dknFKJ8gxWEvGfuS-GnfhnZE',
    appId: '1:349911580596:web:62e0a9003c73e63fbabce1',
    messagingSenderId: '349911580596',
    projectId: 'sukannow-4c072',
    authDomain: 'sukannow-4c072.firebaseapp.com',
    storageBucket: 'sukannow-4c072.firebasestorage.app',
    measurementId: 'G-SG46FZ7NM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHLimqUk2KslNDob7VimIYpLunOuNI7PM',
    appId: '1:349911580596:android:6eec3b4274e3a6cdbabce1',
    messagingSenderId: '349911580596',
    projectId: 'sukannow-4c072',
    storageBucket: 'sukannow-4c072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGMqTpqyKFJuEETTs9qu9JLifvxvwsN8c',
    appId: '1:349911580596:ios:035e2545ef5ad91fbabce1',
    messagingSenderId: '349911580596',
    projectId: 'sukannow-4c072',
    storageBucket: 'sukannow-4c072.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGMqTpqyKFJuEETTs9qu9JLifvxvwsN8c',
    appId: '1:349911580596:ios:035e2545ef5ad91fbabce1',
    messagingSenderId: '349911580596',
    projectId: 'sukannow-4c072',
    storageBucket: 'sukannow-4c072.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY-YRvgK3dknFKJ8gxWEvGfuS-GnfhnZE',
    appId: '1:349911580596:web:b75df0372484c2f0babce1',
    messagingSenderId: '349911580596',
    projectId: 'sukannow-4c072',
    authDomain: 'sukannow-4c072.firebaseapp.com',
    storageBucket: 'sukannow-4c072.firebasestorage.app',
    measurementId: 'G-PD42PQ4F0V',
  );
}
